<a href="https://colab.research.google.com/github/adinovitarini/DiscreteStateSpaceRepresentation/blob/master/DynamProg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dynammic Programming to find shortest problem which implemented in optimal control 

In [36]:
import numpy as np 
from scipy import signal
import matplotlib.pyplot as plt 
#Initialize the initial condition 
#x0 = (0 0)
A = 1
B = 1
C = 1
D = 0
sys1 = signal.StateSpace(A,B,C,D)
print(sys1)
N = 10 #number of iteration 
J = np.zeros(N)
print(J)
for i in range(0,N):
  J[i] = i*0.01
print(J)

StateSpaceContinuous(
array([[1]]),
array([[1]]),
array([[1]]),
array([[0]]),
dt: None
)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09]
